# Copyright 2015 CenturyLink
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Manage load balancer on a data center
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Remove nodes from a load balancer pool
      clc_loadbalancer:
        alias: WFAD
        location: UC1
        name: testlb
        description: testlb1
        state:  nodes_absent
        port: 80
        nodes:
          - {'ipAddress': '10.120.45.14', 'privatePort': 22}
          - {'ipAddress': '10.120.45.15', 'privatePort': 33}
      register: clc
