---
- name: Manage load balancer on a data center
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: add nodes to a load balancer pool
      clc_loadbalancer:
        alias: WFAD
        location: UC1
        name: testlb
        description: testlb1
        state:  nodes_present
        port: 80
        nodes:
          - {'ipAddress': '10.120.45.14', 'privatePort': 22}
          - {'ipAddress': '10.120.45.15', 'privatePort': 44}
      register: clc