---
- name: Create load balancer on a data center
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: create load balancer
      clc_loadbalancer:
        alias: WFAD
        location: WA1
        name: testlb
        description: testlb
        state:  present
        port: 80
        nodes:
          - {'ipAddress': '10.82.152.18', 'privatePort': 11}
          - {'ipAddress': '10.82.152.19', 'privatePort': 22}
      register: clc